# Site wide configuration

title: " 罗家濠的个人学习网站"
description: "期末专案作业"
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: zh_TW 
url:
feed:
  path: atom.xml

# Site owner
owner:
  name: 罗家濠
  email: 461487060@qq.com
  twitter: 
  google:
    ad-client:
    ad-slot:
  bio: "网络与新媒体学生"
  avatar: LUOJIAHAO.jpg
  disqus-shortname:


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
